---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routinator
spec:
  interval: 1h
  path: ./kubernetes/apps/routinator/routinator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: routinator
    namespace: routinator
  targetNamespace: routinator
