---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    extraEnvFrom:
      - configMapRef:
          name: homepage

    volumes:
      - name: &volume-config homepage-configs
        configMap:
          name: homepage-configs
      - name: &volume-images images
        configMap:
          name: homepage-images
    volumeMounts:
      - name: *volume-config
        mountPath: /app/config/settings.yaml
        subPath: settings.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/bookmarks.yaml
        subPath: bookmarks.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/services.yaml
        subPath: services.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/widgets.yaml
        subPath: widgets.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/kubernetes.yaml
        subPath: kubernetes.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/docker.yaml
        subPath: docker.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/custom.css
        subPath: custom.css
        readOnly: true
      - name: *volume-config
        mountPath: /app/config/custom.js
        subPath: custom.js
        readOnly: true
      - name: *volume-images
        mountPath: /app/public/images/unicornafk.svg
        subPath: unicornafk.svg
        readOnly: true
      - name: *volume-images
        mountPath: /app/public/images/background.svg
        subPath: background.svg
        readOnly: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "vault"
        cert-manager.io/private-key-algorithm: "RSA"
        cert-manager.io/private-key-size: "4096"
      hosts:
        - host: &host homepage.unicornafk.fr
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: homepage.unicornafk.fr-tls
      ingressClassName: ingress-internal
