---
# renovate: datasource=github-tags depName=PowerDNS/pdns
powerdns_recursor_repo_version: "rec-5.3.0"
# powerdns_recursor_version:
powerdns_recursor_repository_key: FD380FBB
powerdns_recursor_package_state: latest
powerdns_recursor_webserver_password: password
powerdns_recursor_zones: []
powerdns_recursor_reverse_zones: []
powerdns_recursor_rpz_files:
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.txt

# powerdns_recursor_zones:
#   - unicornafk.fr
#   - adminafk.fr
#   - as212510.net
# powerdns_recursor_reverse_zones:
#   - 4.168.192.in-addr.arpa
#   - 5.168.192.in-addr.arpa
#   - 10.168.192.in-addr.arpa
