---
# renovate: datasource=docker depName=docker.cloudsmith.io/isc/docker/kea-dhcp4
kea_dhcp_version: "3.1.2"
kea_dhcp_repo_gpg_key: 63D408891D8B8D01
# kea_dhcp_hooks_version:
kea_dhcp_hooks_package_state: latest
# kea_dhcp_v4_version:
kea_dhcp_v4_package_state: latest
# kea_dhcp_v6_version:
kea_dhcp_v6_package_state: latest
# kea_dhcp_ctrl_agent_version:
kea_dhcp_ctrl_agent_package_state: latest
kea_dhcp_api_user: ""
kea_dhcp_api_password: ""
kea_dhcp_local_path_ca_certificate: "/tmp/ca.crt"
kea_dhcp_ca_filename: "ca.crt"
kea_dhcp_cert_filename: "example.fr.crt"
kea_dhcp_key_filename: "example.fr.key"
kea_dhcp_ansible_group: dhcp
kea_dhcp_dns_ansible_group: dns
kea_dhcp_dns_domains: []
kea_dhcp_ipv4_subnets: []
kea_dhcp_ipv6_subnets: []
kea_dhcp_ipv4_ntp_servers: []
kea_dhcp_ipv6_ntp_servers: []
kea_dhcp_ipv4_unifi_controller: ""
kea_dhcp_ipv6_unifi_controller: ""
# kea_dhcp_dns_domains:
#   - example.com
# kea_dhcp_ipv4_subnets:
#   - id: 1
#     subnet: 192.168.50.0/24
#     pools:
#       - start: 192.168.50.201
#         end: 192.168.50.240
#     router: 192.168.50.2
#     reservations:
#       - hostname: samsung-tv
#         hw_address: 44:5c:e9:9d:8b:28
#         ip_address: 192.168.50.91
# kea_dhcp_ipv6_subnets:
#   - id: 1
#     subnet: 2a0c:b641:02c0:150::/64
#     pools:
#       - start: 2a0c:b641:02c0:150::201
#         end: 2a0c:b641:02c0:150::240
#     reservations:
#       - hostname: samsung-tv
#         hw_address: 44:5c:e9:9d:8b:28
#         ip_address: 2a0c:b641:02c0:150::91
# kea_dhcp_ipv4_ntp_servers:
#   - 192.168.0.1
# kea_dhcp_ipv6_ntp_servers:
#   - 2a0c:b641:02c0::
# kea_dhcp_ipv4_unifi_controller: 192.168.0.1
# kea_dhcp_ipv6_unifi_controller: 2a0c:b641:02c0::
