---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - ./namespace.yaml
  - ./bazarr/kustomization.yaml
  - ./flaresolverr/kustomization.yaml
  - ./jellyfin/kustomization.yaml
  - ./joal/kustomization.yaml
  - ./prowlarr/kustomization.yaml
  - ./qbittorrent/kustomization.yaml
  - ./radarr/kustomization.yaml
  - ./recyclarr/kustomization.yaml
  - ./seerr/kustomization.yaml
  - ./sonarr/kustomization.yaml
