---
podAnnotations:
  reloader.stakater.com/auto: "true"
rtrService:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.10.103,2a0c:b641:2c0:110::103
serviceMonitor:
  enabled: true
prometheusRule:
  enabled: true
