---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
spec:
  interval: 1h
  path: ./kubernetes/apps/metallb-system/metallb-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb-system
    namespace: metallb-system
  targetNamespace: metallb-system
