---
galaxy_info:
  role_name: openssh_server
  author: Ludovic Ortega
  description: Install and configure openssh_server
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
