---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: as212510-net
spec:
  chartRef:
    kind: OCIRepository
    name: as212510-net
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    extraEnvFrom:
      - configMapRef:
          name: as212510-net
      - secretRef:
          name: as212510-net-openbao
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: ASN
        gethomepage.dev/name: AS212510.net website
        gethomepage.dev/description: AS212510.net website
      hosts:
        - host: &host as212510.net
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: as212510.net-tls
      ingressClassName: ingress-external
    serviceMonitor:
      enabled: true
