---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-api-crds

resources:
  - ./namespace.yaml
  - ./gateway-api-crds/ks.yaml
