---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hyperglass
spec:
  interval: 1h
  path: ./kubernetes/apps/hyperglass/hyperglass/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: hyperglass
    namespace: hyperglass
  targetNamespace: hyperglass
