---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  chartRef:
    kind: OCIRepository
    name: trust-manager
  interval: 1h
  values:
    replicaCount: 2
    app:
      metrics:
        service:
          enabled: true
          ipFamilyPolicy: "PreferDualStack"
          servicemonitor:
            enabled: true
      webhook:
        service:
          ipFamilyPolicy: "PreferDualStack"
    secretTargets:
      enabled: true
      authorizedSecrets:
        - homelab-ca
