---
galaxy_info:
  role_name: kube_vip
  author: Ludovic Ortega
  description: Install and configure kube_vip
  license: CeCILL
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
