---
galaxy_info:
  role_name: ca_certificates
  author: Ludovic Ortega
  description: Install and configure ca_certificates
  license: CeCILL
  min_ansible_version: "2.18.7"
  platforms:
    - name: Ubuntu
      versions:
        - noble
