---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
spec:
  interval: 1h
  path: ./kubernetes/apps/gateway-api-crds/gateway-api-crds/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-crds
    namespace: gateway-api-crds
  targetNamespace: gateway-api-crds
