---
galaxy_info:
  role_name: opentelemetry_collector
  author: Ludovic Ortega
  description: Install and configure opentelemetry_collector
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
