---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private
spec:
  addresses:
    - 192.168.10.100-192.168.10.120
    - 2a0c:b641:02c0:110::100-2a0c:b641:02c0:110::120
  autoAssign: true
  avoidBuggyIPs: false
