---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: routinator
spec:
  chartRef:
    kind: OCIRepository
    name: routinator
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    rtrService:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.10.103,2a0c:b641:2c0:110::103
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
