---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-internal
spec:
  interval: 1h
  path: ./kubernetes/apps/ingress-internal/ingress-internal/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-internal
    namespace: ingress-internal
  targetNamespace: ingress-internal
