---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickwit
spec:
  chart:
    spec:
      chart: quickwit
      version: 0.7.18
      sourceRef:
        kind: HelmRepository
        name: quickwit
      interval: 5m
  interval: 1h
  values:
    searcher:
      replicaCount: 1
    indexer:
      replicaCount: 1
    metastore:
      replicaCount: 1
    janitor:
      enabled: true
    control_plane:
      enabled: true

    podAnnotations:
      reloader.stakater.com/auto: "true"

    environmentFrom:
      - configMapRef:
          name: quickwit-env
      - secretRef:
          name: quickwit-bucket
      - configMapRef:
          name: quickwit-bucket

    config:
      storage:
        s3:
          region: eu-west1
          flavor: minio
          endpoint: http://${BUCKET_HOST}

      metastore_uri: s3://${BUCKET_NAME}/indexes
      default_index_root_uri: s3://${BUCKET_NAME}/indexes

      indexer:
        enable_otlp_endpoint: true

    service:
      ipFamilyPolicy: "PreferDualStack"

    serviceMonitor:
      enabled: true

    prometheusRule:
      enabled: true
