---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: as212510-net
spec:
  interval: 1h
  path: ./kubernetes/apps/as212510-net/as212510-net/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: as212510-net
    namespace: as212510-net
  targetNamespace: as212510-net
