---
galaxy_info:
  role_name: powerdns_recursor
  author: Ludovic Ortega
  description: Install and configure powerdns_recursor
  license: CeCILL
  min_ansible_version: "2.18.7"
  platforms:
    - name: Ubuntu
      versions:
        - noble
