---
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_version: "v1.33.5+k3s1"
k3s_force_install: false
k3s_localhost_kubeconfig_path: /home/user/.kube/kubeconfig
k3s_ha_controlplane_ip: "192.168.0.1,2001:cafe:41:0::"
k3s_join_url: "https://k3s.example.fr:6443"
k3s_nodename: "node"
k3s_ansible_master_group: "kubernetes_master"
k3s_cluster_cidr_ipv4: "10.42.0.0/16"
k3s_cluster_cidr_ipv6: "2001:cafe:42:0::/96"
k3s_service_cidr_ipv4: "10.43.0.0/16"
k3s_service_cidr_ipv6: "2001:cafe:42:1::/112"
k3s_issuer_url: ""
k3s_client_id: ""
