---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hyperglass
spec:
  chartRef:
    kind: OCIRepository
    name: hyperglass
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    extraEnvFrom:
      - configMapRef:
          name: hyperglass
      - secretRef:
          name: &secret-ref hyperglass-openbao

    volumes:
      - name: &volume-config hyperglass-files
        configMap:
          name: hyperglass-files
      - name: &volume-devices hyperglass-devices
        secret:
          secretName: hyperglass-devices-openbao
    volumeMounts:
      - name: *volume-config
        mountPath: /etc/hyperglass/config.yaml
        subPath: config.yaml
        readOnly: true
      - name: *volume-devices
        mountPath: /etc/hyperglass/devices.yaml
        subPath: devices.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/directives.yaml
        subPath: directives.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/greeting.md
        subPath: greeting.md
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/unicornafk.svg
        subPath: unicornafk.svg
        readOnly: true

    valkey:
      auth:
        enabled: true
        existingSecret: *secret-ref
        existingSecretPasswordKey: "HYPERGLASS_REDIS_PASSWORD"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: ASN
        gethomepage.dev/name: Hyperglass
        gethomepage.dev/description: Looking glass
      hosts:
        - host: &host lg.as212510.net
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: lg.as212510.net-tls
      ingressClassName: ingress-external
