---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  chartRef:
    kind: OCIRepository
    name: actualbudget
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    data:
      persistence:
        volumeName: actualbudget-chart-data

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "vault"
        cert-manager.io/private-key-algorithm: "RSA"
        cert-manager.io/private-key-size: "4096"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Other
        gethomepage.dev/name: Actualbudget
        gethomepage.dev/description: Finance manager
      hosts:
        - host: &host actualbudget.unicornafk.fr
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: actualbudget.unicornafk.fr-tls
      ingressClassName: ingress-internal
