---
galaxy_info:
  role_name: dnsdist
  author: Ludovic Ortega
  description: Install and configure dnsdist
  license: CeCILL
  min_ansible_version: "2.19.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
