---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    nameOverride: "external-dns-internal"
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    registry: txt
    txtOwnerId: "homelab.kubernetes"
    provider: "pdns"
    domainFilters:
      - unicornafk.fr
    env:
      - name: EXTERNAL_DNS_INGRESS_CLASS
        value: ingress-internal
      - name: EXTERNAL_DNS_DEFAULT_TARGETS
        value: |-
          192.168.10.101
          2a0c:b641:2c0:110::101
      - name: EXTERNAL_DNS_PDNS_TLS_ENABLED
        value: "true"
      - name: EXTERNAL_DNS_TLS_CA
        value: /etc/external-dns/ssl/ca.crt
      - name: EXTERNAL_DNS_PDNS_SERVER
        valueFrom:
          secretKeyRef:
            name: vault
            key: EXTERNAL_DNS_PDNS_SERVER
      - name: EXTERNAL_DNS_PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: vault
            key: EXTERNAL_DNS_PDNS_API_KEY
    extraVolumes:
      - name: vault
        secret:
          secretName: vault
      - name: "homelab-ca"
        configMap:
          name: "homelab-ca"
    extraVolumeMounts:
      - name: "homelab-ca"
        mountPath: /etc/external-dns/ssl
        readOnly: true
    service:
      ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
