---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pvc-backup
spec:
  sourcePVC: actualbudget-chart-data
  trigger:
    # At 0 minutes past the hour, every 6 hours
    schedule: "0 */6 * * *"
  restic:
    pruneIntervalDays: 14
    repository: pvc-backup-openbao
    retain:
      hourly: 1
      daily: 4
      weekly: 2
      monthly: 4
      yearly: 1
    copyMethod: Snapshot
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: &uid 65534
      runAsGroup: *uid
      fsGroup: *uid
    customCA:
      key: ca.crt
      secretName: homelab-ca
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: pvc-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: pvc-backup-openbao
    destinationPVC: actualbudget-chart-data
    copyMethod: Direct
    accessModes: ["ReadWriteOnce"]
    cleanupCachePVC: true
    cleanupTempPVC: true
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: &uid 65534
      runAsGroup: *uid
      fsGroup: *uid
    customCA:
      key: ca.crt
      secretName: homelab-ca
