---
galaxy_info:
  role_name: uptime_kuma
  author: Ludovic Ortega
  description: Install and configure uptime_kuma
  company: Ludovic Ortega
  license: CeCILL
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
