---
galaxy_info:
  role_name: apt
  author: Ludovic Ortega
  description: Install and configure apt
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
