---
galaxy_info:
  role_name: argocd
  author: Ludovic Ortega
  description: Install and configure argocd
  license: CeCILL
  min_ansible_version: "2.18.7"
  platforms:
    - name: Ubuntu
      versions:
        - noble
