---
galaxy_info:
  role_name: fail2ban
  author: Ludovic Ortega
  description: Install and configure fail2ban
  license: CeCILL
  min_ansible_version: "2.19.3"
  platforms:
    - name: Ubuntu
      versions:
        - noble
