---
galaxy_info:
  role_name: fail2ban
  author: Ludovic Ortega
  description: Install and configure fail2ban
  license: CeCILL
  min_ansible_version: "2.18.8"
  platforms:
    - name: Ubuntu
      versions:
        - noble
