---
galaxy_info:
  role_name: systemd_resolved
  author: Ludovic Ortega
  description: Install and configure systemd_resolved
  license: CeCILL
  min_ansible_version: "2.19.3"
  platforms:
    - name: Ubuntu
      versions:
        - noble
