---
galaxy_info:
  role_name: kubectl
  author: Ludovic Ortega
  description: Install and configure kubectl
  license: CeCILL
  min_ansible_version: "2.19.2"
  platforms:
    - name: Ubuntu
      versions:
        - noble
