---
galaxy_info:
  role_name: ntp
  author: Ludovic Ortega
  description: Install and configure node_exporter
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
