---
galaxy_info:
  role_name: ufw
  author: Ludovic Ortega
  description: Install and configure ufw
  license: CeCILL
  min_ansible_version: "2.18.8"
  platforms:
    - name: Ubuntu
      versions:
        - noble
