---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
spec:
  interval: 1h
  path: ./kubernetes/apps/trust-manager/trust-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: trust-manager
    namespace: trust-manager
  targetNamespace: trust-manager
