---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-external
spec:
  interval: 1h
  path: ./kubernetes/apps/ingress-external/ingress-external/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-external
    namespace: ingress-external
  targetNamespace: ingress-external
