---
galaxy_info:
  role_name: k3s
  author: Ludovic Ortega
  description: Install and configure k3s
  license: CeCILL
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
