---
galaxy_info:
  role_name: runrestic
  author: Ludovic Ortega
  description: Install and configure runrestic
  company: Ludovic Ortega
  license: CeCILL
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
