---
galaxy_info:
  role_name: caddy
  author: Ludovic Ortega
  description: Install and configure Caddy
  company: Ludovic Ortega
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
