---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./kea-exporter/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./opentelemetry-operator/ks.yaml
  - ./prometheus-blackbox-exporter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./prometheus-pve-exporter/ks.yaml
  - ./prometheus-smartctl-exporter/ks.yaml
  - ./prometheus-snmp-exporter/ks.yaml
  - ./quickwit/ks.yaml
  - ./victoria-metrics-single/ks.yaml
