---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &namespace openbao

helmCharts:
  - name: openbao
    releaseName: openbao
    namespace: *namespace
    repo: oci://ghcr.io/openbao/charts/openbao
    version: 0.19.2
    valuesFile: values.yaml
