---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    nameOverride: "external-dns-external"
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    registry: txt
    txtOwnerId: "homelab.kubernetes"
    provider: "scaleway"
    external_dns_domain_filters:
      - adminafk.fr
      - as212510.net
    env:
      - name: EXTERNAL_DNS_INGRESS_CLASS
        value: ingress-external
      - name: EXTERNAL_DNS_DEFAULT_TARGETS
        value: |-
          82.65.135.80
          2a0c:b641:2c0:110::100
      - name: SCW_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: vault
            key: SCW_ACCESS_KEY
      - name: SCW_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: vault
            key: SCW_SECRET_KEY
    extraVolumes:
      - name: vault
        secret:
          secretName: vault
    service:
      ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
