---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openbao

resources:
  - ./namespace.yaml
  - ./openbao/ks.yaml
