---
galaxy_info:
  role_name: vault
  author: Ludovic Ortega
  description: Install and configure vault
  license: CeCILL
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
