---
galaxy_info:
  role_name: kea_dhcp
  author: Ludovic Ortega
  description: Install and configure kea_dhcp
  license: CeCILL
  min_ansible_version: "2.19.3"
  platforms:
    - name: Ubuntu
      versions:
        - noble
