---
collections:
  - name: ansible.utils
    version: "6.0.0"
  - name: ansible.posix
    version: "2.0.0"
  - name: community.general
    version: "10.7.0"
  - name: community.crypto
    version: "2.26.2"
  - name: community.postgresql
    version: "4.1.0"
  - name: community.proxmox
    version: "0.1.0"
  - name: kubernetes.core
    version: "5.3.0"
