---
galaxy_info:
  role_name: nodejs
  author: Ludovic Ortega
  description: Install and configure nodejs
  company: Ludovic Ortega
  license: CeCILL
  min_ansible_version: "2.19.3"
  platforms:
    - name: Ubuntu
      versions:
        - noble
