---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-scaleway
spec:
  chart:
    spec:
      chart: scaleway-certmanager-webhook
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: scw
      interval: 5m
  interval: 1h
  values:
    secret:
      externalSecretName: "cert-manager-scaleway-secret"
    service:
      ipFamilyPolicy: "PreferDualStack"
