---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kea-exporter
spec:
  interval: 1h
  path: ./kubernetes/apps/observability/kea-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability
    namespace: observability
  targetNamespace: observability
