---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease_1.yaml
  - ./helmrelease_2.yaml
  - ./ocirepository.yaml
  - ./certificate.yaml
  - ./configmap.yaml
