---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stirling-pdf
spec:
  interval: 1h
  path: ./kubernetes/apps/stirling-pdf/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: stirling-pdf
    namespace: stirling-pdf
  targetNamespace: stirling-pdf
