---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-smb
spec:
  interval: 1h
  path: ./kubernetes/apps/csi-driver-smb/csi-driver-smb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-driver-smb
    namespace: csi-driver-smb
  targetNamespace: csi-driver-smb
