---
# renovate: datasource=github-tags depName=PowerDNS/pdns
dnsdist_repo_version: "dnsdist-2.0.0"
# dnsdist_version:
dnsdist_repository_key: FD380FBB
dnsdist_package_state: latest
dnsdist_local_path_ca_certificate: "/etc/ssl/certs/ca.crt"
dnsdist_ca_filename: "ca.crt"
dnsdist_cert_filename: "example.fr.crt"
dnsdist_key_filename: "example.fr.key"
dnsdist_api_key: api_key
dnsdist_doh_proxified: false
