---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manage-scaleway

resources:
  - ./namespace.yaml
  - ./cert-manage-scaleway/ks.yaml
