---
galaxy_info:
  role_name: modprobe
  author: Ludovic Ortega
  description: Install and configure modprobe
  license: CeCILL
  min_ansible_version: "2.18.7"
  platforms:
    - name: Ubuntu
      versions:
        - noble
