apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kubelet
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
subsets:
  - addresses:
      - ip: 192.168.10.81
      - ip: 192.168.10.82
      - ip: 192.168.10.83
      - ip: 192.168.10.91
      - ip: 192.168.10.92
      - ip: 192.168.10.93
    ports:
      - name: https-metrics
        port: 10250
        protocol: TCP
