---
galaxy_info:
  role_name: swap
  author: Ludovic Ortega
  description: Install and configure swap
  license: CeCILL
  min_ansible_version: "2.19.2"
  platforms:
    - name: Ubuntu
      versions:
        - noble
