---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kured
spec:
  interval: 1h
  path: ./kubernetes/apps/kured/kured/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kured
    namespace: kured
  targetNamespace: kured
