---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  chartRef:
    kind: OCIRepository
    name: traefik
  interval: 1h
  values:
    deployment:
      replicas: 3
      annotations:
        reloader.stakater.com/auto: "true"
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
        middlewares:
          - ingress-external-security@kubernetescrd
      websecure:
        middlewares:
          - ingress-external-security@kubernetescrd
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.10.100,2a0c:b641:2c0:110::100
      ipFamilyPolicy: PreferDualStack
    providers:
      kubernetesCRD:
        ingressClass: ingress-external
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: ingress-external
    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--providers.kubernetesingress.ingressclass=ingress-external"
    # Already configured by ingress-internal and it can't be configured twice for now
    # see: https://github.com/traefik/traefik-helm-chart/issues/1317
    # tlsOptions:
    #   default:
    #     minVersion: VersionTLS12
    #     cipherSuites:
    #       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    #       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    #       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    #       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    #     sniStrict: true
    metrics:
      prometheus:
        service:
          enabled: true
        disableAPICheck: false
        serviceMonitor:
          enabled: true
