---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pve-exporter-alerts
spec:
  groups:
    - name: PVEAlerts
      rules:
        - alert: PVEExporterDown
          expr: up{job="prometheus-pve-exporter"} != 1
          for: 5m
          labels:
            severity: critical
          annotations:
            description: "PVE exporter instance {{$labels.instance}} from job {{$labels.job}} is down."
            summary: PVE exporter instance down.
