---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stakater
spec:
  chartRef:
    kind: OCIRepository
    name: stakater
  interval: 1h
  values:
    reloader:
      readOnlyRootFileSystem: true
      serviceMonitor:
        enabled: true
