---
galaxy_info:
  role_name: powerdns_authoritative
  author: Ludovic Ortega
  description: Install and configure powerdns_authoritative
  license: CeCILL
  min_ansible_version: "2.19.4"
  platforms:
    - name: Ubuntu
      versions:
        - noble
