---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-smb
provisioner: smb.csi.k8s.io
parameters:
  source: //nas.unicornafk.fr/Multimedia
  csi.storage.k8s.io/node-stage-secret-name: csi-driver-smb-openbao
  csi.storage.k8s.io/node-stage-secret-namespace: csi-driver-smb
volumeBindingMode: Immediate
mountOptions:
  - vers=3.0
  - dir_mode=0777
  - file_mode=0777
  - uid=3000
  - gid=3000
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
