---
galaxy_info:
  role_name: systemd_timesyncd
  author: Ludovic Ortega
  description: Install and configure systemd_timesyncd
  license: CeCILL
  min_ansible_version: "2.18.7"
  platforms:
    - name: Ubuntu
      versions:
        - noble
